#!/usr/bin/env bash
#install nginx and configure the http header
#shellchech SC2154 ignored

sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i "15i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx restart
