#!/usr/bin/env bash
#Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
#Debugging skills

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#sed -i 's/8080 default/80 default/g' /etc/nginx/sites-enabled/default
sudo service nginx start
