#!/usr/bin/env bash
#script that prints "Best School" 10times on terminal
#+using while and if-elif-else to display bad luck at
#+ iter 4 abd good luck at iter 8

a=1
while [ $a -le 20 ]
do
	echo $a
	case $a in
	4)
		echo "bad luck from China"
		;;

	9)
	
		echo "bad luck from Japan"
		;;

	17)
		echo "bad luck from Italy "
		;;
	esac
	((a++))
done
