#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes
#+display hours from 0 to 12
#+display minutes from 1 to 59
#+You must use the while loop (for and until are forbidden)

hr=0
while [ $hr -le 12 ]
do
	echo "Hour: $hr"
	min=1
	while [ $min -lt 60 ]
	do
		echo "$min"
		((min++))
	done
	((hr++))
done
