#!/usr/bin/env bash
#Bash Script that configures Ubuntu Server

cp /etc/hosts ~/hosts.new
sed -i s/127.0.01/127.0.0.2/ ~/hosts.new
echo "8.8.8.8 facebook.com">> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
