#!/usr/bin/env bash
#bash script that;
#nginx must be running as nginx user
#nginx must be listening on all active IPs on port 8080
#You cannot use apt-get remove
sudo chmod 0644 /etc/nginx/nginx.conf
pkill -f apache2
sudo sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-enabled/default
sudo nginx -t
sudo systemctl restart nginx
