#!/usr/bin/env bash
#compressing task#1
sudo chown 0644 /etc/nginx/nginx.conf
pkill -f apache2
sudo sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/nginx.conf
sudo -u nginx service restart nginx
